services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2026.9.1@sha256:47d3a747b958eb798a9d246726e1526d4143fb85ba864e13c5558e4f067bdcfe
    privileged: true
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
